/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utspemvis;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author KHUSNUR FAIZZAH
 */
public class UTS extends javax.swing.JFrame {

    
    Border pink_border = Borderfactory.createMatteBorder(1, 1, 1, 1, Color.pink)
    Border blue_border = Borderfactory.createMatteBorder(1, 1, 1, 1, Color.blue)
            
    /**
     * Creates new form UTS
     */
    public UTS() {
        initComponents();
        
        Jlabel_lyou.setBorder(pink.border);
        Jlabel_lcom.setBorder(blue.border);
        Jlabel_.setBorder(pink.border);
        Jlabel_.setBorder(pink.border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        kotakyou = new javax.swing.JLabel();
        kotakcom = new javax.swing.JLabel();
        lmenang = new javax.swing.JLabel();
        lkalah = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lyou = new javax.swing.JLabel();
        lcom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 153, 204));
        panel1.setLayout(null);

        kotakyou.setBackground(new java.awt.Color(204, 204, 255));
        kotakyou.setOpaque(true);
        panel1.add(kotakyou);
        kotakyou.setBounds(20, 80, 150, 90);

        kotakcom.setBackground(new java.awt.Color(204, 204, 255));
        kotakcom.setOpaque(true);
        panel1.add(kotakcom);
        kotakcom.setBounds(410, 80, 140, 90);

        lmenang.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lmenang.setForeground(new java.awt.Color(255, 51, 204));
        lmenang.setText("0");
        panel1.add(lmenang);
        lmenang.setBounds(180, 90, 40, 60);

        lkalah.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lkalah.setForeground(new java.awt.Color(255, 51, 51));
        lkalah.setText("0");
        panel1.add(lkalah);
        lkalah.setBounds(380, 100, 30, 40);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("-");
        panel1.add(jLabel5);
        jLabel5.setBounds(270, 100, 30, 30);

        jLabel6.setBackground(new java.awt.Color(255, 204, 255));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panel1.add(jLabel6);
        jLabel6.setBounds(60, 230, 110, 80);

        jLabel7.setBackground(new java.awt.Color(255, 204, 255));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panel1.add(jLabel7);
        jLabel7.setBounds(240, 230, 110, 80);

        jLabel8.setBackground(new java.awt.Color(255, 204, 255));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panel1.add(jLabel8);
        jLabel8.setBounds(417, 230, 110, 80);

        lyou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyou.setText("You");
        panel1.add(lyou);
        lyou.setBounds(20, 50, 150, 16);

        lcom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcom.setText("Computer");
        panel1.add(lcom);
        lcom.setBounds(410, 50, 140, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Layout
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel kotakcom;
    private javax.swing.JLabel kotakyou;
    private javax.swing.JLabel lcom;
    private javax.swing.JLabel lkalah;
    private javax.swing.JLabel lmenang;
    private javax.swing.JLabel lyou;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
